### ISSUE TITLE
Question Transfomer & Jasmine

### ISSUE THREAD

**Issue by LukasMachetanz** [Typescript-TDD/jasmine-ts-auto-mock#37]
Hi! 

First of all I would like to apologize for using this channel of communication but I wanted to give it a try. 

Currently I am fiddling around with my own TypeScript Transformer in the case of my thesis. Apparently you guys have a lot of experience with this topic because of this awesome project. Therefore I wanted to ask the following:

It should be possible to access Jasmine in the TypeScript Transformer, right? Currently I am a little bit out of ideas tough how to achieve this. Therefore I wanted to ask if you guys have any tipps, explanations or references for me. I would really appreciate it. 

What I would like to try in the first step is to transform all methods of a specific class to a Jasmine Spy. But as I said, currently I have the problem to get a hold of the Jasmine instance. 

Trying the Transformer in an Angular project I always get `jasmine is not defined`. 

Thanks in advance. 
Greets, Lukas

**Comment by uittorio** [comment]
@LukasMachetanz  No problem at all :) You can write any issue. 

I would recommend to ask any question about the library in the slack channel. You can find the invitation link [here](https://join.slack.com/t/typescripttdd/shared_invite/enQtODk3MjQwNzUwNTk2LTMzNjdlZTNmMmY3Nzg2NDNiZDA1YzJmZjk2NjcwZjQwODQ3YzE5NGZjM2Q4MzZjYWNiMWE4MGU0NjEzM2E5YzE)
We are more than happy to help. If you need any more specific help about transformer there are some typescript channels in [gitter](https://gitter.im/Microsoft/TypeScript)

Saying that I recommend reopening the discussion in slack because I'm not sure what is the issue you are having. You could also provide more information about the dependencies, and some code examples.

I'll close this issue :)

PS: It looks like what you are trying to achieve is what ts-auto-mock does :)
